$("buildBtn").addEventListener("click",async()=>{
  const btn=$("buildBtn");try{
    btn.disabled=true;setStatus("กำลังเตรียมไฟล์...");
    const ns=cleanId($("namespace").value,"hm"),item=cleanId($("itemName").value,"customer_model"),identifier=`${ns}:${item}`;
    const geometryId=`geometry.${ns}.${item}`,animationId=`animation.${ns}.${item}.idle_motion`,version=parseVersion($("version").value);
    const packName=$("packName").value.trim()||"Customer Model",author=$("author").value.trim()||"Unknown";
    const outputBase=lyFileBase($("customerFileName")?.value,"Customer_Head");
    const controllerEnabled=$("enableController")?.checked===true,controllerItem=controllerCleanId($("controllerItemName")?.value,"character_controller"),controllerDisplayName=$("controllerDisplayName")?.value.trim()||"Character Controller",controllerMenuTitle=$("controllerMenuTitle")?.value.trim()||"เลือกสีหน้า",controllerMenuBody=$("controllerMenuBody")?.value.trim()||"เลือกสีหน้าที่ต้องการใช้",expressions=getExpressions();
    let geometry,texture,icon,animation=null,sources=[];
    if(mode==="bbmodel"){
      geometry=convertBBGeometry(bbData,geometryId);
      texture=extractEmbeddedTexture(bbData)||$("fallbackTexture").files[0];
      if(!texture)throw new Error("ไม่พบ Texture กรุณาเพิ่ม Texture สำรอง");
      icon=texture;if($("useAnimation").checked)animation=convertBBAnimations(bbData,animationId);
      if($("includeSource").checked&&bbSourceFile)sources.push(bbSourceFile);
    }else{
      geometry=JSON.parse(JSON.stringify(manualGeoData));
      const geos=geometry["minecraft:geometry"];if(!Array.isArray(geos)||!geos.length)throw new Error("ไม่พบ minecraft:geometry");
      geos[0].description=geos[0].description||{};geos[0].description.identifier=geometryId;
      texture=$("textureFile").files[0];icon=$("iconFile").files[0]||texture;
      if($("useAnimation").checked&&$("animationFile").files[0])animation=JSON.parse(await $("animationFile").files[0].text());
      if($("includeSource").checked)for(const id of ["geoFile","textureFile","iconFile","animationFile"])if($(id).files[0])sources.push($(id).files[0]);
    }

    const rpHeader=uuid(),rpModule=uuid(),bpHeader=uuid(),bpModule=uuid(),slot=$("slot").value;
    const bpModules=[{type:"data",uuid:bpModule,version}],bpDependencies=[{uuid:rpHeader,version}];
    if(controllerEnabled){
      bpModules.push({type:"script",language:"javascript",entry:"scripts/main.js",uuid:uuid(),version});
      bpDependencies.push({module_name:"@minecraft/server",version:"1.16.0"},{module_name:"@minecraft/server-ui",version:"1.3.0"});
    }
    const bpManifest={format_version:2,header:{name:`${packName} BP [${item}]`,description:`Generated by Rabbit Builder • ${author}`,uuid:bpHeader,version,min_engine_version:[1,21,0]},modules:bpModules,dependencies:bpDependencies};
    const rpManifest={format_version:2,header:{name:`${packName} RP [${item}]`,description:`Generated by Rabbit Builder • ${author}`,uuid:rpHeader,version,min_engine_version:[1,21,0]},modules:[{type:"resources",uuid:rpModule,version}]};
    const itemJson={format_version:"1.21.0","minecraft:item":{description:{identifier,menu_category:{category:"equipment"}},components:{"minecraft:display_name":{value:`item.${identifier}.name`},"minecraft:icon":{textures:{default:item}},"minecraft:wearable":{slot,dispensable:true},"minecraft:max_stack_size":1}}};
    const expressionRenderId=`controller.render.${ns}.${item}`;
    const desc={identifier,materials:{default:"entity_alphatest"},textures:{default:`textures/entity/${item}`},geometry:{default:geometryId},render_controllers:[controllerEnabled?expressionRenderId:"controller.render.item_default"]};
    if(animation){desc.animations={custom_animation:animationId};desc.scripts={animate:["custom_animation"]}}
    if($("hideHelmet").checked){desc.scripts=desc.scripts||{};desc.scripts.parent_setup="variable.helmet_layer_visible = 0.0;"}
    const attachable={format_version:"1.10.0","minecraft:attachable":{description:desc}};
    const atlas={resource_pack_name:`${packName} RP`,texture_name:"atlas.items",texture_data:{[item]:{textures:`textures/items/${item}`}}};

    const bp=new JSZip(),rp=new JSZip();
    bp.file("manifest.json",JSON.stringify(bpManifest,null,2));
    bp.folder("items").file(`${item}.json`,JSON.stringify(itemJson,null,2));
    rp.file("manifest.json",JSON.stringify(rpManifest,null,2));
    rp.folder("attachables").file(`${item}.json`,JSON.stringify(attachable,null,2));
    rp.folder("models/entity").file(`${item}.geo.json`,JSON.stringify(geometry,null,2));
    rp.folder("textures/entity").file(`${item}.png`,texture);
    rp.folder("textures/items").file(`${item}.png`,icon);
    rp.folder("textures").file("item_texture.json",JSON.stringify(atlas,null,2));
    rp.folder("texts").file("languages.json",JSON.stringify(["en_US","th_TH"],null,2));
    rp.folder("texts").file("en_US.lang",`item.${identifier}.name=${$("displayEn").value||packName}\n`);
    rp.folder("texts").file("th_TH.lang",`item.${identifier}.name=${$("displayTh").value||packName}\n`);
    if(animation)rp.folder("animations").file(`${item}.animation.json`,JSON.stringify(animation,null,2));
    if(controllerEnabled){
      const cid=`${ns}:${controllerItem}`;
      const cj={format_version:"1.21.0","minecraft:item":{description:{identifier:cid,menu_category:{category:"items"}},components:{"minecraft:display_name":{value:`item.${cid}.name`},"minecraft:icon":{textures:{default:item}},"minecraft:max_stack_size":1,"minecraft:hand_equipped":true}}};
      bp.folder("items").file(`${controllerItem}.json`,JSON.stringify(cj,null,2));
      bp.folder("scripts").file("main.js",makeControllerScript(ns,controllerItem,controllerMenuTitle,controllerMenuBody,expressions,$("autoGiveController")?.checked===true));
      rp.folder("render_controllers").file(`${item}.render_controllers.json`,JSON.stringify(makeExpressionRenderController(ns,item,expressions),null,2));
      rp.folder("texts").file("en_US.lang",`item.${identifier}.name=${$("displayEn").value||packName}\nitem.${cid}.name=${controllerDisplayName}\n`);
      rp.folder("texts").file("th_TH.lang",`item.${identifier}.name=${$("displayTh").value||packName}\nitem.${cid}.name=${controllerDisplayName}\n`);
    }

    const dep=bpManifest.dependencies[0];
    if(dep.uuid!==rpManifest.header.uuid||JSON.stringify(dep.version)!==JSON.stringify(rpManifest.header.version))throw new Error("Dependency validation failed");
    setStatus("กำลังสร้าง BP.mcpack...");
    const bpBlob=await bp.generateAsync({type:"blob",compression:"DEFLATE"});
    setStatus("กำลังสร้าง RP.mcpack...");
    const rpBlob=await rp.generateAsync({type:"blob",compression:"DEFLATE"});
    const addon=new JSZip();
    addon.file(`${outputBase}_BP.mcpack`,bpBlob);
    addon.file(`${outputBase}_RP.mcpack`,rpBlob);
    if(sources.length){const s=addon.folder("source_files");for(const f of sources)s.file(f.name,f)}
    if($("includeReadme").checked)addon.file("README_TH.txt",`แพ็ก: ${packName}\nไอเทม: ${identifier}\nGeometry: ${geometryId}\nคำสั่ง: /give @s ${identifier} 1\nชื่อไฟล์: ${outputBase}.mcaddon\n`);
    setStatus("กำลังรวม .mcaddon...");
    const blob=await addon.generateAsync({type:"blob",compression:"DEFLATE"});
    download(blob,`${outputBase}.mcaddon`);
    setStatus(`สร้างสำเร็จ: ${outputBase}.mcaddon`);
  }catch(e){setStatus("เกิดข้อผิดพลาด: "+e.message)}finally{refresh()}
});
updateIds();refresh();
